# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_time', models.TimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('blood_group', models.CharField(choices=[('Positive (+ve)', (('o+', 'O+'), ('a+', 'A+'), ('b+', 'B+'), ('ab+', 'AB+'))), ('Negetive (-ve)', (('o-', 'O-'), ('a-', 'A-'), ('b-', 'B-'), ('ab-', 'AB-')))], max_length=3)),
                ('contact_number', models.CharField(max_length=15)),
                ('admission_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('amount_total', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('due_date', models.DateField()),
                ('is_prospective', models.BooleanField()),
                ('is_assistive', models.BooleanField()),
                ('is_problematic', models.BooleanField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCategory',
            fields=[
                ('student_category_name', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('category', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('total_tests', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('test_number', models.PositiveSmallIntegerField()),
                ('marks', models.PositiveSmallIntegerField()),
                ('student_roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
                ('test_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.TestCategory')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentCategory'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='attending_students',
            field=models.ManyToManyField(to='students.Student'),
        ),
    ]
