# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.PositiveSmallIntegerField()),
                ('test_description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.TestCategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='testparticipation',
            name='test_category',
        ),
        migrations.RemoveField(
            model_name='testparticipation',
            name='test_number',
        ),
        migrations.AddField(
            model_name='testparticipation',
            name='test',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='students.Test'),
            preserve_default=False,
        ),
    ]
