# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20170207_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_description',
            field=models.TextField(null=True),
        ),
    ]
