# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20170208_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testparticipation',
            old_name='student_roll',
            new_name='student',
        ),
    ]
