# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20170208_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_number', models.SmallIntegerField()),
            ],
            options={
                'ordering': ['category', 'sheet_number'],
            },
        ),
        migrations.CreateModel(
            name='SheetCategory',
            fields=[
                ('category', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'sheet categories',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='SheetDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.ManyToManyField(to='students.SheetCategory')),
            ],
            options={
                'ordering': ['student'],
            },
        ),
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['batch_time'], 'verbose_name_plural': 'batches'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['department_name']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll']},
        ),
        migrations.AlterModelOptions(
            name='studentcategory',
            options={'ordering': ['student_category_name'], 'verbose_name_plural': 'student categories'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['category', 'test_number']},
        ),
        migrations.AlterModelOptions(
            name='testcategory',
            options={'ordering': ['category'], 'verbose_name_plural': 'test categories'},
        ),
        migrations.AlterModelOptions(
            name='testparticipation',
            options={'ordering': ['student', 'test']},
        ),
        migrations.RenameField(
            model_name='test',
            old_name='test_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='testcategory',
            name='total_tests',
        ),
        migrations.AlterField(
            model_name='student',
            name='is_assistive',
            field=models.BooleanField(verbose_name='well-wisher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_problematic',
            field=models.BooleanField(verbose_name='problematic'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_prospective',
            field=models.BooleanField(verbose_name='prospective'),
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together=set([('category', 'test_number')]),
        ),
        migrations.AddField(
            model_name='sheetdistribution',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.SheetCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='sheet',
            unique_together=set([('category', 'sheet_number')]),
        ),
    ]
