# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20170216_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheetdistribution',
            name='sheet',
            field=models.ManyToManyField(to='students.Sheet'),
        ),
    ]
