# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20170216_1933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SheetDistribution',
            new_name='SheetReception',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['roll', 'name']},
        ),
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='attending_students',
            new_name='students',
        ),
    ]
