# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20170220_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sheetreception',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testparticipation',
            options={},
        ),
        migrations.RenameField(
            model_name='sheetreception',
            old_name='sheet',
            new_name='sheets',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='students',
            field=models.ManyToManyField(related_name='attendance_record_set', to='students.Student'),
        ),
        migrations.AlterField(
            model_name='sheetreception',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='received_sheets', to='students.Student'),
        ),
        migrations.AlterField(
            model_name='testparticipation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_participation_set', to='students.Student'),
        ),
    ]
